### ISSUE TITLE
Enabling the Bluetooth with Voice Combo is not working

### ISSUE THREAD

**Issue by asokfair** [Picovoice/picovoice-demo-psoc6#8]
I have created voice project, on top the code added Bluetooth Service /MESH and the code does not compile.

**Comment by kenarsa** [comment]
can you provide more information? also, this issue might be relevant to the Bluetooth repo as this seems like a firmware problem vs a voice engine problem.

**Comment by mrrostam** [comment]
Closed due to inactivity
